name: Build

on: [push, pull_request]

jobs:
  windows_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
                
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc patch m4 lzip curl tar make diffutils unzip
      - uses: actions/checkout@v3
      - name: Checkout ARB repo
        uses: actions/checkout@v3
        with:
          repository: fredrik-johansson/arb
          path: arb
      - name: Build Dependencies
        shell: msys2 {0}
        run: bin/cibw_before_build_windows.sh
        
      - uses: actions/upload-artifact@v2
        with:
          path: .local/*
